DATA_PATH: 'data/'
#LLM: 'starling-lm:7b-alpha-q3_K_M'
LLM: 'starling-lm:7b-alpha-q5_K_M'
EMBEDDINGS: 'sentence-transformers/all-mpnet-base-v2'
WEAVIATE_URL: 'http://localhost:8080'
INDEX_NAME: 'Sparrow'
CHUNK_SIZE: 1000
#OLLAMA_BASE_URL: 'http://192.168.68.110:11434'
OLLAMA_BASE_URL: 'http://127.0.0.1:11434'